# build stage
FROM node:12-alpine3.9 as build-stage

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm cache clean --force
RUN npm install

COPY . .

RUN npm run build:vagrant

# production stage
FROM nginx:stable-alpine as production-stage

COPY ./nginx/conf/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080

ENTRYPOINT ["nginx"]