# build stage
FROM node:12-alpine3.9 as build-stage

WORKDIR /usr/src/app

COPY production ./production
COPY dist ./dist

WORKDIR /usr/src/app/production

RUN npm cache clean --force
RUN npm install

ENTRYPOINT [ "npm", "run", "start" ]